CREATE TABLE IF NOT EXISTS "nauticaius_bronzewater_npc_table" (
    "name" TEXT,
    "race" TEXT,
    "class" TEXT,
    "age" NUMERIC(4, 1),
    "height" TEXT,
    "alignment" TEXT,
    "affiliation" TEXT,
    "first_appearance" NUMERIC(3, 1),
    "str" INT,
    "dex" INT,
    "con" INT,
    "int" INT,
    "wis" INT,
    "cha" INT,
    "description" INT
);
INSERT INTO "nauticaius_bronzewater_npc_table" VALUES
    ('Cailyn Levanna','Wood Elf','Druid (Shepard)',100.0,'4''8"','CG',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Cascerra','Firbolg',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Jack Crowe','Human',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Silas Kierhe/Levi Avales','Human',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Marlin Silverfish','Human','Wizard (Divination)',26.0,'5''11"','NG','The Stormchasers,The Crow''s Nest',1.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Gizmo Gallantgear','Rock Gnome','Mechanist',49.0,'3''2"','CG','The League of Artisans',1.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Daryn Jerricus','Half-Elf','Accountant',24.0,'5''4"','LG','The Stormchasers,The Crow''s Nest',2.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Jin Vel Mai','Stout Halfling','Monk (Drunken Master)',35.0,'3''0"','CN',NULL,4.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Mottengallius Redfellow','Mountain Dwarf','Cleric (Forge Domain)',256.0,'4''5"','LN','The League of Artisans',5.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Celestini Giovantis','Half-Elf','Paladin (Redemption)',25.0,'5''4"','CG','The Vindicators',5.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Grigori Giovantis','Half-Elf','Fighter (Eldritch Knight)',25.0,'5''10"','CG','The Vindicators',6.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Atesios Craine','Wood Elf','Cleric (Knowledge)',361.0,'5''11"','LN','The Divine Order of Saldonis',6.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Hessia Kafta','Triton','The Pontificator',144.0,'5''5"','LE','The Divine Order of Saldonis',6.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Remington Gallantgear','Rock Gnome','Gunslinger',49.0,'3''1"','CN','The League of Artisans',7.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Rev','Kobold','Librarian,Sorcerer (Draconic)',20.0,'2''3"','LG','University of Bronzewater',8.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Kalakani Elianafosten','High Elf','CEO of the Talos Robot Corp.,Wizard (Transmutation)',289.0,'5''9"','TN','The Talos Robot and Mechanical Entity Corporation',8.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Darius Stormchosen','Human','Bard (Swords)',24.0,'5''9"','CG',NULL,8.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Frank','Warforged','Cleric (War)',1.0,'7''0"','LG','The Talos Robot and Mechanical Entity Corporation',8.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Evelyn Fairdew','High Elf','Supreme Architect of the League of Artisans,Wizard (Abjuration)',280.0,'5''3"','NG','The League of Artisans',9.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Olivia Kierhe/Avales','Half-Elf','Rogue (Thief)',30.0,'5''7"','NG','(former) The Silhouette,The Crow''s Nest',9.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Maya Kierhe/Avales','Half-Elf',NULL,6.0,'3''5"','LG',NULL,9.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Ivana the Stalker','Kenku','Ranger (Gloom Stalker)',46.0,'4''0"','TN','Silverfalls',13.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Dorivantes Yasrani','High Elf','Rogue',NULL,NULL,'NE','The Silhouette',13.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Talith Levanna','Wood Elf','Bard (Lore)',529.0,NULL,'CG',NULL,13.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Dr. Markus Valhelm','High Elf','History Professor,Wizard (Necromancy)',NULL,NULL,'TN','University of Bronzewater',15.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Vani Elianafosten','High Elf',NULL,NULL,NULL,'CN','The Talos Robot and Mechanical Entity Corporation',16.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Barb','Human(?)','Druid (Moon)',NULL,'6''8"','CE',NULL,17.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Voris Baneriver','Goliath','Mandate of Bronzewater',NULL,'8''0"','LE','The Divine Order of Saldonis',17.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Haley Hallia','Forest Gnome','Header Admin of the TRC',NULL,'2''10"',NULL,'The Talos Robot and Mechanical Entity Corporation',18.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Hex','Goblin','Artillerist',NULL,NULL,NULL,NULL,20.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Begonia Demetris','Half-Orc','Monk (Open Hand)',NULL,NULL,NULL,NULL,20.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Rima','Water Genasi','Rogue (Assassin)',NULL,NULL,NULL,NULL,21.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Dodwin','Tortle','Master Architect of the League of Artisans',NULL,NULL,NULL,'The League of Artisans',22.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Tasha Thunderberry','Stout Halfling','Student,Librarian',NULL,NULL,NULL,'University of Bronzewater',23.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    ('Delonius Allihandris','Half-Orc','Student,Librarian',NULL,NULL,'CN','University of Bronzewater',24.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
