# Generated by Django 2.2.7 on 2019-11-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0002_auto_20191107_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('alignment', models.TextField(blank=True, null=True)),
                ('affiliation', models.TextField(blank=True, null=True)),
                ('first_appearance', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('str', models.IntegerField(blank=True, null=True)),
                ('dex', models.IntegerField(blank=True, null=True)),
                ('con', models.IntegerField(blank=True, null=True)),
                ('int', models.IntegerField(blank=True, null=True)),
                ('wis', models.IntegerField(blank=True, null=True)),
                ('cha', models.IntegerField(blank=True, null=True)),
                ('description', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nauticaius_bronzewater_npc_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='NauticaiusBronzewaterNpcTable',
        ),
        migrations.DeleteModel(
            name='NpcsNpc',
        ),
    ]
