# Generated by Django 2.2.7 on 2019-11-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0003_auto_20191107_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={},
        ),
    ]
