# Generated by Django 2.2.7 on 2019-11-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0004_auto_20191107_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'managed': False},
        ),
    ]
