# Generated by Django 2.2.7 on 2019-11-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0005_auto_20191107_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'managed': True},
        ),
    ]
